call c:\xml.bat
cd X54
call xml2txt -v X54 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X55
call xml2txt -v X55 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X56
call xml2txt -v X56 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X57
call xml2txt -v X57 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X58
call xml2txt -v X58 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X59
call xml2txt -v X59 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X60
call xml2txt -v X60 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X61
call xml2txt -v X61 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X62
call xml2txt -v X62 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X63
call xml2txt -v X63 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X64
call xml2txt -v X64 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X65
call xml2txt -v X65 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X66
call xml2txt -v X66 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X67
call xml2txt -v X67 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X68
call xml2txt -v X68 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X69
call xml2txt -v X69 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X70
call xml2txt -v X70 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X71
call xml2txt -v X71 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X72
call xml2txt -v X72 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X73
call xml2txt -v X73 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X74
call xml2txt -v X74 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X75
call xml2txt -v X75 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X76
call xml2txt -v X76 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X77
call xml2txt -v X77 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X78
call xml2txt -v X78 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X79
call xml2txt -v X79 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X80
call xml2txt -v X80 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X81
call xml2txt -v X81 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X82
call xml2txt -v X82 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X83
call xml2txt -v X83 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X84
call xml2txt -v X84 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X85
call xml2txt -v X85 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X86
call xml2txt -v X86 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X87
call xml2txt -v X87 -u -h -k -z -x 2
cd c:\cbwork\xml
cd X88
call xml2txt -v X88 -u -h -k -z -x 2
cd c:\cbwork\xml
